main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }
    
producto:
    path:     /list/{id}
    defaults: { _controller: MainBundle:Producto:index , id: null}
    
producto_show:
    path:     /producto/{id}
    defaults: { _controller: MainBundle:Producto:show }
    
administracion_show:
    path:     /administracion
    defaults: { _controller: MainBundle:Administracion:index }
    
administracion_new_user:
    path:     /administracion/new/user/
    defaults: { _controller: MainBundle:Administracion:newUser }
    
administracion_remove_user:
    path:     /administracion/remove/user/{id}
    defaults: { _controller: MainBundle:Administracion:removeUser }
    
administracion_edit_user:
    path:     /administracion/edit/user/{id}
    defaults: { _controller: MainBundle:Administracion:editUser }
    
administracion_edit_password_user:
    path:     /administracion/edit/user/password/{id}
    defaults: { _controller: MainBundle:Administracion:editPasswordUser }
    
administracion_new_category:
    path:     /administracion/category/new
    defaults: { _controller: MainBundle:Administracion:newCategory }
    
administracion_remove_category:
    path:     /administracion/category/remove/{id}
    defaults: { _controller: MainBundle:Administracion:removeCategory }
    
administracion_edit_category:
    path:     /administracion/category/edit/{id}
    defaults: { _controller: MainBundle:Administracion:editCategory }
    
administracion_new_product:
    path:     /administracion/product/new
    defaults: { _controller: MainBundle:Administracion:newProduct }
    
administracion_remove_product:
    path:     /administracion/product/remove/{id}
    defaults: { _controller: MainBundle:Administracion:removeProduct }
    
administracion_edit_product:
    path:     /administracion/product/edit/{id}
    defaults: { _controller: MainBundle:Administracion:editProduct }
